### ISSUE TITLE
index ships a public `bench` executable

### ISSUE THREAD

**Issue by NathanReb** [mirage/index#388]
It seems that in recent versions, index started shipping a binary called bench.

If this is intentionally public, prefixing its name would help avoiding conflicts. If it's not it, making it private would be best to avoid any future problems.

This has been causing troubles in projects using opam-monorepo as index is not the only one doing so, meaning vendoring it alongside those other packages causes dune to have multiple rules to build the bench executable.

I suspect this should be a private executable, used for benchmarking in index only. There are a few tricks you can use in dune to be able to refer to a private executable as if it was public. If that may help you can see how we do this in opam-monorepo:
https://github.com/ocamllabs/opam-monorepo/blob/main/test/bin/dune#L9.

Let me know if I can help with this in any way!

**Comment by NathanReb** [comment]
ocamlformat also does this at the moment, see: https://github.com/ocaml-ppx/ocamlformat/issues/2100

**Comment by avsm** [comment]
This should definitely be a private executable, not something installed to the public file manifest.

**Comment by NathanReb** [comment]
A rename works just as well for me! I'll submit a PR!
