### ISSUE TITLE
Improvements to db_bench

### ISSUE THREAD

**Issue by samoht** [mirage/index#93]
Here is a few comments on `db_bench`:

- [x] simplify bench output #94 
- [x] remove `file size` values for write amplification as they don't mean much (especially for lmdb)
- [x] add number of operations per seconds (reads and writes) as in https://blog.dgraph.io/post/badger-lmdb-boltdb/
- [ ] add a raw output to ease the generation of graphs if wanted
- [x] check what can be merged with https://github.com/mirage/index/pull/49 to simplify the use of metrics events.

**Comment by samoht** [comment]
Also related to https://github.com/mirage/index/pull/49

**Comment by pascutto** [comment]
Fixed by #151
